### ISSUE TITLE
Also how to change the texture of the Stamina?

### ISSUE THREAD

**Issue by makumaku1974** [murphy-slaw/staminafortweakers#13]

**Comment by murphy-slaw** [comment]
Currently the stamina bar is drawn with GUI drawing commands. An upcoming release will have the option to use a texture instead, at which point you can override the texture with a resource pack.

**Comment by murphy-slaw** [comment]
This is deployed to Modrinth in 1.2.0. See the Changeling for the assets to override in your resource pack.
