### ISSUE TITLE
Pressing W once causes to sprint 1.21 on latest update.

### ISSUE THREAD

**Issue by makumaku1974** [murphy-slaw/staminafortweakers#15]

**Comment by murphy-slaw** [comment]
Confirmed. I made an error when converting the codebase from Yarn to Mojang mappings. ClientPlayerEntity.canSprint -> LocalPlayer.hasEnoughFoodToStartSprinting(), but I injected into LocalPlayer.canStartSprinting() instead.

This is an easy fix. I will have a build up shortly.

**Comment by murphy-slaw** [comment]
Posted to Modrinth and Curseforge as 1.2.1.
