### ISSUE TITLE
Stamina bar not disappearing with F1

### ISSUE THREAD

**Issue by Tenuuu** [murphy-slaw/staminafortweakers#17]
![image](https://github.com/murphy-slaw/staminafortweakers/assets/93273736/9661caf9-543c-43d6-ac10-054b23254841)

As seen in the image, the stamina bar is still present when the F1 button is active

**Comment by makumaku1974** [comment]
Same with mine.
![2024-07-02_19 59 20](https://github.com/murphy-slaw/staminafortweakers/assets/129804277/8d9d4f11-73e5-44fb-a26e-7a079f97b80c)
