### ISSUE TITLE
1.21 Recipe for crafting potion of tirelessness is gone... (EMI)

### ISSUE THREAD

**Issue by makumaku1974** [murphy-slaw/staminafortweakers#21]
Somehow only the uses for it is visible but the not the main crafting recipe.

![image](https://github.com/user-attachments/assets/c461e6dc-14aa-4051-b878-2111e283f784)

**Comment by murphy-slaw** [comment]
Confirmed, potion recipe registration changed in 1.21 and my updated code was wrong.

**Comment by murphy-slaw** [comment]
Fixed in 1.3.2
