### ISSUE TITLE
Farmer delight 

### ISSUE THREAD

**Issue by Felisinnn** [murphy-slaw/staminafortweakers#29]
The player could be encouraged to cook if cooking complex dishes rewarded them with the tirelessness effect. 
Maybe a way to make the implementation simpler and compatible with the gazillion addons would be to make it so that every consumable which gives the nourishment effect also gives tirelessness?

**Comment by murphy-slaw** [comment]
This is an interesting idea. I need to look at the Farmer's Delight code but it should be posssible to add this as a toggleable option.

**Comment by murphy-slaw** [comment]
I started working on this and I realized that there's no reason that I had to hardcode the specific Farmer's Delight effect.

I just released version 1.4.0, which allows you to define *any* effect from Minecraft or a mod as equivalent to Tirelessness.
