### ISSUE TITLE
1.21 BUG |  Wind Charge Levitation

### ISSUE THREAD

**Issue by makumaku1974** [murphy-slaw/staminafortweakers#6]
IDK if you have tested it yourself but at the right timing of launching myself witih wind charge i levitation for like 40 blocks high.

**Comment by makumaku1974** [comment]
Not just wind charge but when you take damage by jumping into a campfire the i-frame timing just activates the levitation with this mod. I thought it was the Wall-Jump mod that was causing this problem and it wasn't.

**Comment by murphy-slaw** [comment]
Can you recreate this effect with only this mod installed? If not, could you share your mod list?

**Comment by murphy-slaw** [comment]
Can you describe the problem in more detail? I have tried to recreate this in a test environment with only this mod installed and I haven't managed to find any combination of actions that causes levitation or floating with wind charges. They seem to act normally when the player is at full stamina and when the player is exhausted a wind charge can barely lift them off the ground.

**Comment by makumaku1974** [comment]
No need actually... You kinda fixed it with the next update.

**Comment by makumaku1974** [comment]
> Can you recreate this effect with only this mod installed? If not, could you share your mod list?

The problem is that i have about 300 mods already... haha

**Comment by murphy-slaw** [comment]
Going to close this one out then. Out of curiosity, which version had this problem?

**Comment by murphy-slaw** [comment]
Resolving this for now.

**Comment by makumaku1974** [comment]
> Going to close this one out then. Out of curiosity, which version had this problem?

I think before you added the Exhaustion, Fatigue, and Attack Stamina. But it got another with one mod specifically. Idk if you have heard about Just Hammers? It's a good mod for excavating 5x5x5 blocks but with your mod The Fatigue enhances and causes the player to not regain stamina. Which is yeah I have to basically die everytime i use the hammer.

**Comment by makumaku1974** [comment]
![2024-06-22_21 01 38](https://github.com/murphy-slaw/staminafortweakers/assets/129804277/1ecbe89e-5244-4108-9469-7be887c449b7)

This is what i was talking about right now.

**Comment by murphy-slaw** [comment]
Can you open a new issue for this? I'll take a look.

**Comment by makumaku1974** [comment]
> Can you open a new issue for this? I'll take a look.

ok then.
