### ISSUE TITLE
Mods that break multiple blocks at once make stamina unable to regenerate

### ISSUE THREAD

**Issue by makumaku1974** [murphy-slaw/staminafortweakers#7]
I have mods like Falling Tree, and Just Hammers which you know they automatically depletes your stamina quickly. 

![2024-06-22_21 01 38](https://github.com/murphy-slaw/staminafortweakers/assets/129804277/3ce4e2c3-a048-4164-9ade-71a1672eb1e8)
![2024-06-22_21 05 32](https://github.com/murphy-slaw/staminafortweakers/assets/129804277/22aa784f-35b4-4a6c-96e4-c8eafba4e267)

**Comment by makumaku1974** [comment]
Should i check logs?

**Comment by murphy-slaw** [comment]
Logs would be helpful. Can you also post your `config/staminafortweakers.json5` file from the instance?

**Comment by makumaku1974** [comment]
Actually the stamina is able to regen when it breaks another block LMFAO...

**Comment by murphy-slaw** [comment]
I *think* I know what is going on here. I set a flag that says "the player is mining, consume stamina" when you begin attacking a block, and I unset it when you stop or the block breaks. In vanilla, only one block can ever be mined at a time. These tools break multiple blocks at a time and it is probably messing with the logic in some way that leaves the flag set.

Breaking another block resets the flag. 

I'll test out this theory with Just Hammers installed and see if I can come up with a fix.

**Comment by makumaku1974** [comment]
Here is the demo.
https://github.com/murphy-slaw/staminafortweakers/assets/129804277/fdfd25c0-40b1-4cb2-8fc9-9b02988c846b

**Comment by makumaku1974** [comment]
> I _think_ I know what is going on here. I set a flag that says "the player is mining, consume stamina" when you begin attacking a block, and I unset it when you stop or the block breaks. In vanilla, only one block can ever be mined at a time. These tools break multiple blocks at a time and it is probably messing with the logic in some way that leaves the flag set.
> 
> Breaking another block resets the flag.
> 
> I'll test out this theory with Just Hammers installed and see if I can come up with a fix.

The Just Hammers is actually persistent and cant reset since it breaks multiple at once but with the Falling Trees or any Tree Capitator mods out there can actually reset the Flag.

**Comment by murphy-slaw** [comment]
This fix is in 1.0.9, which I just posted to CurseForge and Modrinth.
